[package]
name = "view_counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
serde = "1.0.215"
sqlx = "0.8.2"
structsy = "0.4"
structsy-derive = "0.4"